x = int(input("x: "))
y = int(input("y: "))

print(f"{x} + {y} = {x + y}")
print(f"{x} - {y} = {x - y}")
print(f"{x} * {y} = {x * y}")
print(f"{x} / {y} = {x / y}")
print(f"{x} % {y} = {x % y}")
print(f"{x} // {y} = {x // y} R {x % y}")
print(f"{x}^{y} = {x**y}")